#pragma once

#include <chronos/price_level.hpp>
#include <chronos/memory_pool.hpp>
#include <chronos/event_publisher.hpp>
#include <map>
#include <unordered_map>
#include <vector>
#include <functional>
#include <algorithm>

namespace chronos {

/**
 * @brief Manages the Limit Order Book (LOB) for a single symbol.
 * 
 * Maintains sorted bids and asks and provides O(1) order lookup/cancellation.
 */
class LimitOrderBook {
public:
    explicit LimitOrderBook(std::pmr::memory_resource* resource, EventPublisher* publisher = nullptr)
        : bids_(resource), asks_(resource), order_lookup_(resource), publisher_(publisher) {}

    /**
     * @brief Process an incoming order: match it against the book or add it.
     * @return List of trades generated by this order.
     */
    std::pmr::vector<Trade> processOrder(Order* order, std::pmr::memory_resource* trade_resource) {
        std::pmr::vector<Trade> trades(trade_resource);

        if (order->side == OrderSide::Buy) {
            matchAgainstAsks(order, trades);
        } else {
            matchAgainstBids(order, trades);
        }

        // If order still has quantity, add to the book
        if (order->quantity.value() > 0) {
            order->status = (order->status == OrderStatus::New) ? OrderStatus::New : OrderStatus::Partial;
            addToBook(order);
        } else {
            order->status = OrderStatus::Filled;
        }

        // Publish Events
        if (publisher_) {
            for (const auto& trade : trades) {
                publisher_->publishTrade(trade);
            }
            publisher_->publishOrderUpdate(*order);
        }

        return trades;
    }

    /**
     * @brief Cancel an order in O(1).
     */
    bool cancelOrder(OrderId id) {
        auto it = order_lookup_.find(id);
        if (it == order_lookup_.end()) {
            return false;
        }

        const auto& entry = it->second;
        if (entry.side == OrderSide::Buy) {
            auto bid_it = bids_.find(entry.price);
            if (bid_it != bids_.end()) {
                bid_it->second.removeOrder(entry.list_iterator);
                if (bid_it->second.empty()) {
                    bids_.erase(bid_it);
                }
            }
        } else {
            auto ask_it = asks_.find(entry.price);
            if (ask_it != asks_.end()) {
                ask_it->second.removeOrder(entry.list_iterator);
                if (ask_it->second.empty()) {
                    asks_.erase(ask_it);
                }
            }
        }

        order_lookup_.erase(it);
        return true;
    }

    const PriceLevel* getBestBid() const {
        return bids_.empty() ? nullptr : &bids_.begin()->second;
    }

    const PriceLevel* getBestAsk() const {
        return asks_.empty() ? nullptr : &asks_.begin()->second;
    }

    std::size_t numBidLevels() const { return bids_.size(); }
    std::size_t numAskLevels() const { return asks_.size(); }
    std::size_t numOrders() const { return order_lookup_.size(); }

private:
    struct OrderEntry {
        Price price;
        PriceLevel::OrderListIterator list_iterator;
        OrderSide side;
    };

    void addToBook(Order* order) {
        if (order->side == OrderSide::Buy) {
            auto [it, inserted] = bids_.try_emplace(order->price, order->price, bids_.get_allocator().resource());
            auto list_it = it->second.addOrder(order);
            order_lookup_[order->id] = {order->price, list_it, OrderSide::Buy};
        } else {
            auto [it, inserted] = asks_.try_emplace(order->price, order->price, asks_.get_allocator().resource());
            auto list_it = it->second.addOrder(order);
            order_lookup_[order->id] = {order->price, list_it, OrderSide::Sell};
        }
    }

    void matchAgainstAsks(Order* order, std::pmr::vector<Trade>& trades) {
        while (order->quantity.value() > 0 && !asks_.empty()) {
            auto best_ask_it = asks_.begin();
            if (order->price < best_ask_it->first) break;

            PriceLevel& level = best_ask_it->second;
            matchLevel(order, level, trades);

            if (level.empty()) {
                asks_.erase(best_ask_it);
            }
        }
    }

    void matchAgainstBids(Order* order, std::pmr::vector<Trade>& trades) {
        while (order->quantity.value() > 0 && !bids_.empty()) {
            auto best_bid_it = bids_.begin();
            if (order->price > best_bid_it->first) break;

            PriceLevel& level = best_bid_it->second;
            matchLevel(order, level, trades);

            if (level.empty()) {
                bids_.erase(best_bid_it);
            }
        }
    }

    void matchLevel(Order* order, PriceLevel& level, std::pmr::vector<Trade>& trades) {
        while (order->quantity.value() > 0 && !level.empty()) {
            Order* matching_order = level.front();
            int64_t match_qty = std::min(order->quantity.value(), matching_order->quantity.value());

            // Create Trade
            Trade trade;
            trade.price = level.price();
            trade.quantity = Quantity(match_qty);
            trade.timestamp = 0; // In production, this would be current time

            if (order->side == OrderSide::Buy) {
                trade.buy_order_id = order->id;
                trade.sell_order_id = matching_order->id;
            } else {
                trade.buy_order_id = matching_order->id;
                trade.sell_order_id = order->id;
            }
            trades.push_back(trade);

            // Update Quantities
            order->quantity = Quantity(order->quantity.value() - match_qty);

            if (matching_order->quantity.value() == match_qty) {
                matching_order->status = OrderStatus::Filled;
                matching_order->quantity = Quantity(0);
                
                if (publisher_) {
                    publisher_->publishOrderUpdate(*matching_order);
                }

                order_lookup_.erase(matching_order->id);
                level.popFront();
            } else {
                matching_order->status = OrderStatus::Partial;
                level.fillFront(match_qty);

                if (publisher_) {
                    publisher_->publishOrderUpdate(*matching_order);
                }
            }
        }
    }

    // Bids: Sorted High -> Low
    std::pmr::map<Price, PriceLevel, std::greater<Price>> bids_;
    // Asks: Sorted Low -> High
    std::pmr::map<Price, PriceLevel, std::less<Price>> asks_;
    
    // Global lookup for O(1) cancellations
    std::pmr::unordered_map<OrderId, OrderEntry> order_lookup_;

    EventPublisher* publisher_;
};

} // namespace chronos
